name: "Setup Python and pixi"
description: "setup Python and pixi with caches"

inputs:
  pixi-environments:
    description: "Pixi environment(s) to install (use a space to separate multiple environments)"
    required: true


runs:
  using: "composite"
  steps:
    - name: Install pixi  # also includes auto-caching
      uses: prefix-dev/setup-pixi@v0.8.1
      with:
        pixi-version: v0.26.1
        cache: false
        # cache: true
        # cache-key: ${{ inputs.pixi-environments }}
        environments: ${{ inputs.pixi-environments }}
        # pre-commit ensures that pixi.lock is up to date with pyproject.toml,
        # hence here we can just follow the lock file exactly
        frozen: true
        # Pixi breaks our entire CI if we use `locked: true` here
        # because it thinks we need to update our lock file
        # when we update our version number in `pyproject.toml`.
        # We check the locked status using the `check-lock-file` job
        # in the CI workflow instead.
        log-level: vv
