name: "Setup Python and pixi"
description: "setup Python and pixi with caches"

inputs:
  os:
    description: "Operating system to use"
    required: false
    default: "ubuntu-latest"
  pixi-environments:
    description: "Pixi environment(s) to install (use a space to separate multiple environments)"
    required: true


runs:
  using: "composite"
  steps:
    - name: Install pixi  # also includes auto-caching
      uses: prefix-dev/setup-pixi@v0.8.1
      with:
        cache: true
        environments: ${{ inputs.pixi-environments }}
        locked: true  # ensure that pixi.lock is up to date with pyproject.toml
