# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.6.2
_src_path: ../copier-core-python-repository
email: zebedee.nicholls@climate-resource.com
initial_setup: true
name: Zebedee Nicholls
notebook_dependencies: true
pandas_doctests: false
plot_dependencies: true
project_description_short: Validation of input4MIPs data (checking file formats, metadata
    etc.).
project_name_human: Input4MIPs-validation
project_name_pip: input4mips-validation
project_name_python: input4mips_validation
project_url: https://github.com/climate-resource/input4mips_validation
track_lock_file: false
