# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9"
  jobs:
    pre_build:
      - pip install --no-deps .
      - input4mips-validation --help
      - typer input4mips_validation.cli utils docs --output docs/cli/index.md --name input4mips-validation
      - python scripts/download-cf-standard-name-table.py
      # Can add other checks in here if things blow up confusingly
    post_install:
      - mamba list

conda:
  environment: environment-docs.yml

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: true
