# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Thank you also https://browniebroke.com/blog/specify-docs-dependency-groups-with-poetry-and-read-the-docs/

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9"
  jobs:
    pre_build:
      - pip install --no-deps .
      - typer input4mips_validation.cli utils docs --output docs/cli/index.md --name input4mips-validation
    post_install:
      - mamba list
      - ls
      - input4mips-validation --help
      - input4mips-validation validate-file --cv-source "gh:main" docs/how-to-guides/fixed_CH4-em-biomassburning_input4MIPs_emissions_CMIP_CR-CMIP-0-2-0_gn_200001-201012.nc --write-in-drs .

conda:
  environment: environment-docs.yml

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: true
