# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Thank you also https://browniebroke.com/blog/specify-docs-dependency-groups-with-poetry-and-read-the-docs/

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9"
  jobs:
    pre_build:
      - pip install --no-deps .
    post_install:
      - mamba list

conda:
  environment: environment-docs.yml

# Set sphinx configuration
sphinx:
   configuration: docs/source/conf.py
