# A sample file, which illustrates how the logging can be configured
# For more details, see:
# - [loguru](https://loguru.readthedocs.io/)
# - [loguru-config](https://github.com/erezinman/loguru-config)

handlers:
  - sink: ext://sys.stderr
    # Some different levels that might be useful
    # level: DEBUG
    # level: INFO_INDIVIDUAL_CHECK
    # level: INFO_INDIVIDUAL_CHECK_ERROR
    # level: INFO_FILE
    # level: INFO_FILE_ERROR
    # level: INFO_DB_ENTRY
    # level: INFO_DB_ENTRY_ERROR
    level: INFO
    colorize: true
    format: "{process} - {thread} - <green>{time:!UTC}</> - <lvl>{level}</> - <cyan>{name}:{file}:{line}</> - <lvl>{message}</>"
  # Log to a file instead of stderr
  # - sink: file_{time}.log
  #   level: DEBUG
  #   enqueue: true
  #   # serialize: true
  #   format: "{process} - {thread} - {time:!UTC} - {level} - {name}:{file}:{line} - {message}"
activation:
  - [ "input4mips_validation", true ]
