name: CI

on:
  pull_request:
  push:
    branches: [main]
    tags: ['v*']

jobs:
  mypy:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          pixi-environments: "all-dev"
      - name: mypy
        run: MYPYPATH=stubs pixi run -e all-dev mypy src

  docs:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          pixi-environments: "docs"
      - name: docs
        run: pixi run -e docs sphinx-build -W --keep-going -T -b html docs/source docs/build

  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest" ]
        test-python-id: [ "py39", "py310", "py311" ]
    runs-on: "${{ matrix.os }}"
    defaults:
      run:
        # This might be needed for Windows and doesn't seem to affect unix-based systems
        # so we include it. If you have better proof of whether this is needed or not,
        # feel free to update.
        shell: bash
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          pixi-environments: "test-${{ matrix.test-python-id }} all-dev"
      - name: Run tests
        run: |
          pixi run -e "test-${{ matrix.test-python-id }}" pytest -r a -v src tests --doctest-modules --cov=src --cov-report=term-missing --cov-report=xml
          pixi run -e "test-${{ matrix.test-python-id }}"  coverage report
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3

  imports-without-extras:
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest" ]
        python-version: [ "3.9", "3.10", "3.11" ]
    runs-on: "${{ matrix.os }}"
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          python-version: "${{ matrix.python-version }}"
          venv-id: "imports-without-extras-${{ runner.os }}"
          poetry-dependency-install-flags: "--only main"
      - name: Check importable without extras
        run: poetry run python scripts/test-install.py

  check-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          python-version: "3.9"
          venv-id: "check-build-${{ runner.os }}"
          run-poetry-install: false
          poetry-dependency-install-flags: "not used"
      - name: Build package
        run: |
          poetry build --no-interaction
      - name: Check build
        run: |
          tar -tvf dist/input4mips_validation-*.tar.gz --wildcards '*input4mips_validation/py.typed'
          tar -tvf dist/input4mips_validation-*.tar.gz --wildcards 'input4mips_validation-*/LICENCE'


  check-dependency-licences:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          python-version: "3.9"
          venv-id: "licence-check"
          poetry-dependency-install-flags: "--all-extras"
      - name: Check licences of dependencies
        shell: bash
        run: |
          TEMP_FILE=$(mktemp)
          poetry export --without=tests --without=docs --without=dev > $TEMP_FILE
          poetry run liccheck -r $TEMP_FILE -R licence-check.txt
          cat licence-check.txt
