name: Test installation conda

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # This means At 03:00 on Wednesday.
    # see https://crontab.guru/#0_0_*_*_3
    - cron:  '0 3 * * 3'

jobs:
  test-micromamba-installation:
    name: Test (micro)mamba install ${{ matrix.install-target }} (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: "${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        # # There is an issue on windows, one for another day
        # os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        os: ["ubuntu-latest", "macos-latest"]
        python-version: [ "3.9", "3.10", "3.11" ]
        # Check both the 'library' and the 'application' (i.e. locked package)
        install-target: ["input4mips-validation", "input4mips-validation-locked"]

    steps:
    # While we wait for conda-forge release
    # (https://github.com/conda-forge/staged-recipes/pull/26986)
    # specify pins by hand
    - name: Setup (micro)mamba and install package
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-name: test-mamba-install
        create-args: >-
          python=${{ matrix.python-version }}
          -c conda-forge
          ${{ matrix.install-target }}
        init-shell: bash
    - name: Get version
      run: |
        INSTALLED_VERSION=`python -c 'import input4mips_validation; print(f"v{input4mips_validation.__version__}")'`
        echo $INSTALLED_VERSION
        echo "INSTALLED_VERSION=$INSTALLED_VERSION" >> $GITHUB_ENV
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        # Make sure that we run the tests that apply to the version we installed.
        # If you don't do this, the tests can fail
        # because tests from main, that rely on new features,
        # will be used to check an old version, so there will likely be failures.
        # That isn't what we want this workflow to test.
        # We want this workflow to test
        # that installing from PyPI/conda leads to a correct installation.
        ref: ${{ env.INSTALLED_VERSION }}
    - name: Test installation
      shell: bash -leo pipefail {0}
      run: |
        which python
        which cfchecks
        python scripts/test-install.py
    - name: Install pytest
      shell: bash -leo pipefail {0}
      run: |
        micromamba install pytest
    - name: Run tests
      shell: bash -leo pipefail {0}
      run: |
        pytest tests -r a -vv -s
