name: Test installation conda

on:
  pull_request:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # This means At 03:00 on Wednesday.
    # see https://crontab.guru/#0_0_*_*_3
    - cron:  '0 3 * * 3'

jobs:
  test-micromamba-installation:
    name: Test (micro)mamba install ${{ matrix.install-target }} (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: "${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        # os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        # python-version: [ "3.9", "3.10", "3.11" ]
        os: ["ubuntu-latest"]
        python-version: [ "3.10" ]
        # Check both 'library' install and the 'application' (i.e. locked) install
        install-target: ["input4mips-validation", "input4mips-validation-locked"]

    steps:
    - name: Setup (micro)mamba and install package
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-name: test-mamba-install
        create-args: >-
          python=${{ matrix.python-version }}
          -c conda-forge
          pip
          "iris==3.8.1"
          "netcdf4==1.7.1"
          "numpy==1.26.4"
          "cfchecker==4.1.0"
          "cf-xarray==0.9.4"
          "loguru==0.7.2"
          "ncdata==0.1.1"
          "pandas==2.2.2"
          "pint==0.24.3"
          "pint-xarray==0.4"
          "pooch==1.8.2"
          "typer==0.12.3"
          "validators==0.33.0"
          "xarray==2024.6.0"
        init-shell: bash
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: No deps install the package
      run: pip install --no-deps "${{ matrix.install-target }}"
    - name: Test installation
      shell: bash -leo pipefail {0}
      run: |
        which python
        which cfchecks
        python scripts/test-install.py
    - name: Install pytest
      shell: bash -leo pipefail {0}
      run: |
        mamba install pytest
    - name: Run tests
      shell: bash -leo pipefail {0}
      run: |
        pytest tests -r a -vv
