name: Test installation PyPI

on:
  pull_request:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # This means At 03:00 on Wednesday.
    # see https://crontab.guru/#0_0_*_*_3
    - cron:  '0 3 * * 3'

jobs:
  test-pypi-install:
    name: Test PyPI install ${{ matrix.install-target }} (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: "${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        # os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        # python-version: [ "3.9", "3.10", "3.11" ]
        os: ["ubuntu-latest"]
        python-version: [ "3.9" ]
        # Check both 'library' install and the 'application' (i.e. locked) install
        install-target: ["input4mips-validation", "input4mips-validation[locked]"]
    steps:
    - name: Set up Python "${{ matrix.python-version }}"
      id: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: "${{ matrix.python-version }}"
    - name: Install (non-windows)
      if: matrix.os != 'windows-latest'
      run: |
        pip install --upgrade pip
        pip install "${{ matrix.install-target }}" 2>stderr.txt
        if grep -q "WARN" stderr.txt; then echo "Warnings in pip install output" && cat stderr.txt && exit 1; else exit 0; fi
    - name: Install (windows)
      if: matrix.os == 'windows-latest'
      run: |
        pip install --upgrade pip
        pip install "${{ matrix.install-target }}"
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Test installation
      run: |
        which python
        python scripts/test-install.py
    - name: Install pytest
      run: |
        pip install pytest
    - name: Run tests
      run: |
        pytest tests -r a -vv
